### ISSUE TITLE
Tonatiuh doesn't show the Flux Distribution

### ISSUE THREAD

**Issue by Sdbabel** [iat-cener/tonatiuh#100]
I ran Tonatiuh in order to show the flux distribution and get the Incidence Flux on one surface but no flux distribution is showed, everything I have is a rectangular distribution of flux with a value of 0. I've changed the parameters of the rays and I have tried other surfaces that I have and no result is showed. Does someone know the solution for this?

Thanks

**Comment by ChileNeverDie** [comment]
Have you seen the rays hitting the surface? you can use "Ray trace">"Run">"Store type - Not export" to see how the ray interact with the surface. Maybe because the ray never arrives the surface...
