### ISSUE TITLE
Define Sun Light - Script Editor 

### ISSUE THREAD

**Issue by felipelobi** [iat-cener/tonatiuh#108]
Hi ! 
 I am working with the tonatiuh Script Editor and I can't find how define the nodes that i don't want to cumpute first stage rays area. I wish I could include these two nodes.

![image](https://user-images.githubusercontent.com/26729853/81139970-bc18c500-8f35-11ea-8aa0-5be15ec9838b.png)

help!

**Comment by amutuberria** [comment]
Hi,
to define these nodes you have to use the "**_SetValue_**" function. There is not a specific funtion for that. In the example that you have proposed the function will be use in the following way:

_tonatiuh.SetValue("//Light", "disabledNodes", "//SunNode/RootNode/SF/concentrator/Tapa;//SunNode/RootNode/SF/foco");_

**Comment by felipelobi** [comment]
Thanks!!
