### ISSUE TITLE
permissible range for slope error values for CPC

### ISSUE THREAD

**Issue by AditiiiGarg** [iat-cener/tonatiuh#121]
I am simulating a CPC model in tonatiuh. I want to add values for optical errors such as slope error and specular error. I understand they need to be entered in specular rough standard material. I would like to know what is the range for these values permissible in tonatiuh. 
Is there any document or text which I could refer for CPC.

I have gone through this document  8.4.3 The Contribution of Errors  (http://www.powerfromthesun.net/Book/chapter08/chapter08.html). However, as per the text they are applicable for parabolic troughs and dishes.

**Comment by amutuberria** [comment]
Hi,
The slope and specular error must be defined in mrad. Define them  as a positive real number for the simulations and there is not limit value.

**Comment by AditiiiGarg** [comment]
thank you amutuberria
