### ISSUE TITLE
Compile Tonatiuh on MacBook Air M2

### ISSUE THREAD

**Issue by ovidiopr** [iat-cener/tonatiuh#123]
Hi,
 I am trying to compile Tonatiuh on a MacBook Air with an M2 processor, following this guide (https://github.com/iat-cener/tonatiuh/wiki/Installing-For-Mac). However, many of the instructions seem to be for an older version of the source code. Do you have any updated guide? If not, could you assist me about how to do it?

Thank you and best regards,

Ovidio

**Comment by amutuberria** [comment]
Sorry, but currently I have not any MAC available to assist you.
