### ISSUE TITLE
ShapeCad crash

### ISSUE THREAD

**Issue by JJP660** [iat-cener/tonatiuh#79]
Hi

I'm studying the effects of external loads on the optics of heliostat mirror panels. Currently, my process is to export a deformed mirror surface from an FEA package in STL format and then import it to Tonatiuh for ray tracing. I've been testing finer mesh sizes to improve ray tracing accuracy resulting in larger STL files. The latest file is 20Mb and Tonatiuh immediately crashes upon import. I've monitored the computer's resources during the import and can't see any issues there. Is there anything else that can limit the CAD import size?

Thanks in advance!

**Comment by ilescener** [comment]
Dear Tonatiuh user,

First of all, I want to apologize for the long delay of the answer.

Does the problem still persist? I've never tried to import STL files as weigh as 20Mb but should work correctly. Does Tonatiuh work when the mesh size is larger and the correspondent STL file is less weight?

Kind regards
Iñigo

**Comment by JJP660** [comment]
Dear Iñigo


Yes, this problem still persists with this particular model. Regarding your second question, yes, when I define the same surface using a coarser mesh (resulting in a smaller file size) then it works without a problem. Can I perhaps send you the problematic file to test?


Regards


________________________________

**Comment by ilescener** [comment]
Yes, You even can send me both files, one file that works perfect (coarse mesh) and the one that doesn't (fine mesh).

Thank you
Iñigo

**Comment by JJP660** [comment]
Thanks Iñigo. Please see both files attached.

Regards



________________________________

**Comment by ilescener** [comment]
I can't see the files. You may have forgotten to upload them or something didn't work properly. Could you do it again, please?

**Comment by JJP660** [comment]
They are both in the zipped file called Paramesh.7z because they are too large to email.

Here they are again. Let me know if you have issues extracting them.

Regards

**Comment by ilescener** [comment]
They are not attached. I guess the files are too large to answer the topic through email. I propose you to upload them to DropBox, for example, and pass the link for downloading them. 

Is it possible?

**Comment by JJP660** [comment]
Hi Iñigo


They can now be downloaded from the following two links:


https://cloudstor.aarnet.edu.au/sender/?vid=140b8eca-0a4f-86a8-fbbb-0000719d31b8

https://cloudstor.aarnet.edu.au/sender/?vid=467fb266-3dda-2929-3a33-00002d9c4c48


Let me know if you have any further problems.


Regards

**Comment by ilescener** [comment]
Hello.

Sorry for the late answer but Github didn't make me know (usually it does) you had answered.

I found the issue, when Tonatiuh tries to import that CAD sufrace some internal variables get their memory full and crashes. I fixed it and attached is a Tonatiuh file with your surface.

In case you want to import more heavy CAD surface don't hesitate in contact me. In spite of that, I hope a new version of Tonatiuh will be released in the next days.

Kind regards
[finepara.zip](https://github.com/iat-cener/tonatiuh/files/467609/finepara.zip)

**Comment by JJP660** [comment]
Thanks for your help!


Regards



________________________________

**Comment by JJP660** [comment]
Hi Iñigo


Is there any indication when the next version containing this fix will be released?


Thanks




________________________________

**Comment by ilescener** [comment]
Hi. We will try to release the new version next week.

**Comment by ilescener** [comment]
Dear user,

The last version of Tonatiuh has just released. Check it here: https://github.com/iat-cener/tonatiuh/releases/tag/2.2.2 Enjoy it!

Iñigo
