### ISSUE TITLE
Rotate a surface (CPC)

### ISSUE THREAD

**Issue by asalim86** [iat-cener/tonatiuh#84]
Hello, I have some problems trying to rotate a CPC reflector. This surface've inserted from the surfaces defined. I was trying to rotate the surface from the bottom right box but did not succeed. I'm using Tonatiuth 2.2.2. and Windows 10. Thanks.
![rotcpc](https://cloud.githubusercontent.com/assets/16179673/19864942/4897054e-9f68-11e6-9597-53905c265e5b.JPG)

**Comment by ilescener** [comment]
Dear user,

Rotations can be defined in "Group Nodes". Just note that the axis of rotation is always in local coordinates (related to this surface), the angle must be introduced in radians and everything which is in that group node will be rotated.
I guess you are trying to make a rotation of the surfaces to get a symmetric figure. So, in the node called "reflector2", introduce a rotation along the y axis (0 1 0 3.14159). 

KR
Iñigo

**Comment by ilescener** [comment]
The other question about the fixed bug calculating the total power in the flux analysis tool. Before this minor correction, the Total Power in the surface was calculated taking into account all rays which arrived to the surface, even if they do it in the no-specified side of the surface. Therefore, it could happen that the Average Flux*AreaOfTheSurface wasn't equal to the Total Power, which doesn't make sense. Of course, this bug only gets importance if the number of rays which arrive the no-specified surfaces were high respect to the correct one.

**Comment by asalim86** [comment]
Dear Iñigo: The question is answered. I really appreciate your help. Thank you. 
SB.
