### ISSUE TITLE
how to cite Tonatiuh in a scientific article

### ISSUE THREAD

**Issue by pierre-haessig** [iat-cener/tonatiuh#89]
Everything is in the title! I wonder if there is an "official" Tonatiuh paper that could be cited when writing a scientific article which results were generated using Tonatiuh. (I'm thinking of something along the lines of https://scipy.org/citing.html)

**Comment by ilescener** [comment]
Dear user,

You can use some of these:

- _Blanco, M., Mutuberria, A., Monreal, A., & Albert, R. (2011). Results of the empirical validation of Tonatiuh at Mini-Pegase CNRS-PROMES facility. Proc SolarPACES._

- _Blanco, M. J., Mutuberria, A., & Martinez, D. (2010). Experimental validation of Tonatiuh using the Plataforma Solar de Almería secondary concentrator test campaign data. In 16th annual SolarPACES symposium._

- _Blanco, M. J., Mutuberria, A., Garcia, P., Gastesi, R., & Martin, V. (2009). Preliminary validation of Tonatiuh SOLARPACES Symposium. Berlin, Germany._

- _Blanco, M. J., Amieva, J. M., & Mancillas, A. (2005, January). The Tonatiuh Software Development Project: An open source approach to the simulation of solar concentrating systems. In ASME 2005 International Mechanical Engineering Congress and Exposition (pp. 157-164). American Society of Mechanical Engineers._

Regards

**Comment by ilescener** [comment]
I agree. I thought the same after your question. I'll do it as soon as possible.

**Comment by pierre-haessig** [comment]
I see the citable articles in the README. Issue can be closed.
