### ISSUE TITLE
Linear Fresnel Tracker

### ISSUE THREAD

**Issue by AbdallahAyman** [iat-cener/tonatiuh#90]
The question is about how the linear Fresnel tracker works , and what are the modification parameters for?. I modeled a Semi parabolic linear Fresnel System, but Once I put the Fresnel tracker in a mirror node it moves the mirror to position 0 0 0 , So how can I add the tracker so it can just tilt the mirror around the z-axis to point the ray reflection towards the cylinder which is hanging up in the middle.

**Comment by ilescener** [comment]
Dear AbdallahAyman

The tracker nodes always change the parent node parameters automatically when a scene light position changes. If you define manually the value of a node and this node has a tracker child, when the light position changes this value will be removed. So, the correct way to do this is by creating a intermediate node for the tracker node. Look at the following screenshot. The position and rotation of the collector has been set in the node called Collector and I have created a node called TrackerNode for allowing the tracker to make its job.

![trackernode](https://user-images.githubusercontent.com/15195244/27591320-98b7c928-5b51-11e7-95a7-a5120a17cd34.png)

Kind regards
Iñigo

**Comment by AbdallahAyman** [comment]
I got it , Thank you for responding ! I have another question for the linear Fresnel tracker plugin , What is the difference between Absolute and relative aiming ? and what are the axis origin parameters used for?

**Comment by ilescener** [comment]
Absolute means that you are setting up the aiming point/line respect to the absolute coordinate system while relative is referring to the coordinate system of the reflectance surface. I really recommend you to use absolute, I think relative aiming is just easier in some very specific cases.
The axis origin means the 2Dpoint in the corresponding plane, for example if the active axis is the Z, this plane is the XY plane.

**Comment by AbdallahAyman** [comment]
Thanks for the reply ! I got it.
