### ISSUE TITLE
Material parameters question

### ISSUE THREAD

**Issue by AbdallahAyman** [iat-cener/tonatiuh#92]
![untitled222](https://user-images.githubusercontent.com/29705281/27968237-7a2bd3c6-6346-11e7-8a25-3f9779f66052.png)
Can some one tell me what is the unit used for sigma slope ? is it mrad or rad or degree? And what is the difference between pillbox and normal in the distribution parameter?

**Comment by ilescener** [comment]
Dear user,

The unit for the sigma slope is the mrad. The pillbox is a probability uniform distribution in the range of [-sigmaSlope, +sigmaSlope] meanwhile the normal is a Gaussian distribution centred in the 0 and with sigmaSlope as a standard deviation. 

I think this kind of information can be found in the Wiki but also we should include some help dialog or some text near the box to make all this information know for the new users.

Regards
Iñigo

**Comment by AbdallahAyman** [comment]
I got it. Thanks for the reply.
Best regards,
Abdallah
