### ISSUE TITLE
Slope and specular errors

### ISSUE THREAD

**Issue by BrandonvanB** [iat-cener/tonatiuh#99]
Good day

When modelling errors in optics, there are generally two primary errors encountered when doing ray-tracing simulations. These are the macro errors (commonly known as slope errors) and micro errors (commonly referred to as specular errors). I see that under the Specular_standard_Material node, it is possible to input a value for slope errors under "m_sigmaslope", which I assume asks the user to enter a slope error value in miliradians. From my understanding, specular errors are affiliated with the material itself and other ray-tracing packages that I have used generate this value when you specify the material type. 

Does Tonatiuh only take into account slope errors or does the "m_sigmaslope" value account for both slope and specular errors? 

Many thanks

**Comment by amutuberria** [comment]
Dear 
If you want to use the two mentioned errors you can use the material called "Specular_Rough_Standard_Material". This material includes the slope and specular errors in milliradians. But if you want to continue using "Specular_standard_Material" you have to calculate the equivalent error for defining only as slope error.

**Comment by BrandonvanB** [comment]
Thank you for your helpful response!
